import { setGlobalOptions } from 'firebase-functions/v2';
import { runtimeAlertRecipientsSecret } from '../../functions/src/notifications/notificationSecrets';
setGlobalOptions({
  secrets: [runtimeAlertRecipientsSecret],
});

import setuserrole from '../../functions/src/setUserRole';
import listusers from '../../functions/src/listUsers';
import getuser from '../../functions/src/getUser';
import getusersbyids from '../../functions/src/getUsersByIds';
import setUserRoleOnCreate, { setUserRoleOnSignIn } from '../../functions/src/setUserRoleOnCreate';
import addtolist from '../../functions/src/addToList';
import removefromlist from '../../functions/src/removeFromList';
import sermonWriteTrigger from '../../functions/src/DocumentListeners/Sermons/sermonWriteTrigger';
import sermonOnDelete from '../../functions/src/DocumentListeners/Sermons/sermonOnDelete';
import listOnDelete from '../../functions/src/DocumentListeners/Lists/listOnDelete';
import listOnUpdate from '../../functions/src/DocumentListeners/Lists/listOnUpdate';
import listItemOnDelete from '../../functions/src/DocumentListeners/Lists/listItemOnDelete';
import listItemOnCreate from '../../functions/src/DocumentListeners/Lists/listItemOnCreate';
import sermonListOnCreate from '../../functions/src/DocumentListeners/SermonLists/sermonListOnCreate';
import sermonListOnDelete from '../../functions/src/DocumentListeners/SermonLists/sermonListOnDelete';
import sermonListOnUpdate from '../../functions/src/DocumentListeners/SermonLists/sermonListOnUpdate';
import updatecreatedandeditedatmillis from '../../functions/src/updateCreatedAndEditedAtMillis';
import fixsermonCounts from '../../functions/src/fixSermonCounts';
import { createTopicBundle } from '../../functions/src/createTopicBundle';
import topicOnWrite from '../../functions/src/DocumentListeners/Topics/topicOnWrite';
import { createSubtitleBundle } from '../../functions/src/createSubtitleBundle';
import subtitleListOnWrite from '../../functions/src/DocumentListeners/Lists/subtitleListOnWrite';
import { createBibleChapterBundle } from '../../functions/src/createBibleChapterBundle';
import { createSundayHomilyBundle } from '../../functions/src/createSundayHomilyBundle';
import { createLatestListBundle } from '../../functions/src/createLatestListBundle';
import { bibleChapterListOnWrite, sundayHomilyListOnWrite } from '../../functions/src/DocumentListeners/Lists/taggedListOnWrite';
import seriesItemOnWrite from '../../functions/src/DocumentListeners/Series/seriesItemOnWrite';
import createrolerequest from '../../functions/src/roleRequests/createRoleRequest';
import listrolerequests from '../../functions/src/roleRequests/listRoleRequests';
import acceptrolerequest from '../../functions/src/roleRequests/acceptRoleRequest';
import denyrolerequest from '../../functions/src/roleRequests/denyRoleRequest';
import createinvite from '../../functions/src/invites/createInvite';
import claiminvite from '../../functions/src/invites/claimInvite';
import listinvites from '../../functions/src/invites/listInvites';
import revokeinvite from '../../functions/src/invites/revokeInvite';
import resendinvite from '../../functions/src/invites/resendInvite';
import createspeaker from '../../functions/src/speakers/createSpeaker';
import updatespeaker from '../../functions/src/speakers/updateSpeaker';
import deletespeaker from '../../functions/src/speakers/deleteSpeaker';
import updateallspeakertags from '../../functions/src/updateAllSpeakerTags';
import getlistoverflowchain from '../../functions/src/getListOverflowChain';
import getlistpublisheddrift from '../../functions/src/getListPublishedDrift';
import marklistoverflowlink from '../../functions/src/markListOverflowLink';
import createseries from '../../functions/src/createSeries';
import deleteseries from '../../functions/src/deleteSeries';
import addtoseries from '../../functions/src/addToSeries';
import removefromseries from '../../functions/src/removeFromSeries';
import reorderseriesitems from '../../functions/src/reorderSeriesItems';
import bulkaddtoseries from '../../functions/src/bulkAddToSeries';
import getseriesremotestate from '../../functions/src/getSeriesRemoteState';
import reorderlistitems from '../../functions/src/reorderListItems';
import resolvelistpublisheddrift from '../../functions/src/resolveListPublishedDrift';

exports.setuserrole = setuserrole;
exports.listusers = listusers;
exports.getuser = getuser;
exports.getusersbyids = getusersbyids;
exports.setuserroleoncreate = setUserRoleOnCreate;
exports.setuserroleonsignin = setUserRoleOnSignIn;
exports.addtolist = addtolist;
exports.removefromlist = removefromlist;
exports.sermonwritetrigger = sermonWriteTrigger;
exports.sermonOnDelete = sermonOnDelete;
exports.listondelete = listOnDelete;
exports.listonupdate = listOnUpdate;
exports.listitemondelete = listItemOnDelete;
exports.listitemoncreate = listItemOnCreate;
exports.sermonlistoncreate = sermonListOnCreate;
exports.sermonlistondelete = sermonListOnDelete;
exports.sermonlistonupdate = sermonListOnUpdate;
exports.updatecreatedandeditedatmillis = updatecreatedandeditedatmillis;
exports.fixsermoncounts = fixsermonCounts;
exports.createtopicbundle = createTopicBundle;
exports.topiconwrite = topicOnWrite;
exports.createsubtitlebundle = createSubtitleBundle;
exports.subtitlelistonwrite = subtitleListOnWrite;
exports.createbiblechapterbundle = createBibleChapterBundle;
exports.createsundayhomilybundle = createSundayHomilyBundle;
exports.createlatestlistbundle = createLatestListBundle;
exports.biblechapterlistonwrite = bibleChapterListOnWrite;
exports.sundayhomilylistonwrite = sundayHomilyListOnWrite;
exports.seriesitemonwrite = seriesItemOnWrite;
exports.createrolerequest = createrolerequest;
exports.listrolerequests = listrolerequests;
exports.acceptrolerequest = acceptrolerequest;
exports.denyrolerequest = denyrolerequest;
exports.createinvite = createinvite;
exports.claiminvite = claiminvite;
exports.listinvites = listinvites;
exports.revokeinvite = revokeinvite;
exports.resendinvite = resendinvite;
exports.createspeaker = createspeaker;
exports.updatespeaker = updatespeaker;
exports.deletespeaker = deletespeaker;
exports.updateallspeakertags = updateallspeakertags;
exports.getlistoverflowchain = getlistoverflowchain;
exports.getlistpublisheddrift = getlistpublisheddrift;
exports.marklistoverflowlink = marklistoverflowlink;
exports.createseries = createseries;
exports.deleteseries = deleteseries;
exports.addtoseries = addtoseries;
exports.removefromseries = removefromseries;
exports.reorderseriesitems = reorderseriesitems;
exports.bulkaddtoseries = bulkaddtoseries;
exports.getseriesremotestate = getseriesremotestate;
exports.reorderlistitems = reorderlistitems;
exports.resolvelistpublisheddrift = resolvelistpublisheddrift;
