// To deploy functions: npm run-script deploy
// To test functions: npm run-script serve
import generatesecuredapikey from './generateAlgoliaSecureApiKey';
import tagitemsinlist from './Scrapers/tagItemsInList';
import updatecreatedandeditedatmillis from './updateCreatedAndEditedAtMillis';
import uploadToSubsplash from './uploadToSubsplash';
import setuserrole from './setUserRole';
import addintrooutrotaskhandler from './addIntroOutro/addintrooutrotaskhandler';
import addintrooutrotaskgenerator from './addIntroOutro/addintrooutrotaskgenerator';
import deleteFromSubsplash from './deleteFromSubsplash';
import uploadimage from './handleImageUpload';
import saveimage from './saveImage';
import getimage from './getImage';
import listusers from './listUsers';
import setUserRoleOnCreate from './setUserRoleOnCreate';
import populatedatabasefromsubsplash from './Scrapers/populateDatabaseFromSubsplash';
import createnewsubsplashlist from './createNewSubsplashList';
import deletesubsplashlist from './deleteSubsplashList';
import editsubsplashlist from './editSubsplashList';
import addtolist from './addToList';
import removefromlist from './removeFromList';
import uploadtosoundcloud from './uploadToSoundCloud';
import deletefromsoundcloud from './deleteFromSoundCloud';
import editSubsplashSermon from './editSubsplashSermon';
import editSoundCloudSermon from './editSoundCloudSermon';
import listItemOnDelete from './DocumentListeners/Lists/listItemOnDelete';
import listItemOnCreate from './DocumentListeners/Lists/listItemOnCreate';
import listOnDelete from './DocumentListeners/Lists/listOnDelete';
import listOnUpdate from './DocumentListeners/Lists/listOnUpdate';
import sermonListOnCreate from './DocumentListeners/SermonLists/sermonListOnCreate';
import sermonListOnDelete from './DocumentListeners/SermonLists/sermonListOnDelete';
import sermonListOnUpdate from './DocumentListeners/SermonLists/sermonListOnUpdate';
import sermonOnDelete from './DocumentListeners/Sermons/sermonOnDelete';
import sermonWriteTrigger from './DocumentListeners/Sermons/sermonWriteTrigger';
import repopulatelistfromspeakeritems from './Scrapers/repopulateListFromSpeakerItems';
import getuser from './getUser';

exports.uploadToSubsplash = uploadToSubsplash;
exports.editSubsplashSermon = editSubsplashSermon;
exports.editSoundCloudSermon = editSoundCloudSermon;
exports.deleteFromSubsplash = deleteFromSubsplash;
exports.setuserrole = setuserrole;
exports.addintrooutrotaskhandler = addintrooutrotaskhandler;
exports.addintrooutrotaskgenerator = addintrooutrotaskgenerator;
exports.uploadimage = uploadimage;
exports.getimage = getimage;
exports.listusers = listusers;
exports.getuser = getuser;
exports.setuserroleoncreate = setUserRoleOnCreate;
exports.populatedatabasefromsubsplash = populatedatabasefromsubsplash;
exports.createnewsubsplashlist = createnewsubsplashlist;
exports.deletesubsplashlist = deletesubsplashlist;
exports.editsubsplashlist = editsubsplashlist;
exports.addtolist = addtolist;
exports.removefromlist = removefromlist;
exports.saveimage = saveimage;
exports.uploadtosoundcloud = uploadtosoundcloud;
exports.deletefromsoundcloud = deletefromsoundcloud;
exports.sermonwritetrigger = sermonWriteTrigger;
exports.sermonOnDelete = sermonOnDelete;
exports.listondelete = listOnDelete;
exports.listonupdate = listOnUpdate;
exports.listitemondelete = listItemOnDelete;
exports.listitemoncreate = listItemOnCreate;
exports.sermonlistoncreate = sermonListOnCreate;
exports.sermonlistondelete = sermonListOnDelete;
exports.sermonlistonupdate = sermonListOnUpdate;
exports.repopulatelistfromspeakeritems = repopulatelistfromspeakeritems;
exports.updatecreatedandeditedatmillis = updatecreatedandeditedatmillis;
exports.tagitemsinlist = tagitemsinlist;
exports.generatesecuredapikey = generatesecuredapikey;
