// To deploy functions: npm run-script deploy
// To test functions: npm run-script serve
import { setGlobalOptions } from 'firebase-functions/v2';
import { runtimeAlertRecipientsSecret } from './notifications/notificationSecrets';
setGlobalOptions({
  secrets: [runtimeAlertRecipientsSecret],
});

import generatesecuredapikey from './generateAlgoliaSecureApiKey';
import tagitemsinlist from './Scrapers/tagItemsInList';
import updatecreatedandeditedatmillis from './updateCreatedAndEditedAtMillis';
import uploadToSubsplash from './uploadToSubsplash';
import setuserrole from './setUserRole';
import addintrooutrotaskhandler from './addIntroOutro/addintrooutrotaskhandler';
import addintrooutrotaskgenerator from './addIntroOutro/addintrooutrotaskgenerator';
import deleteFromSubsplash from './deleteFromSubsplash';
import uploadimage from './handleImageUpload';
import saveimage from './saveImage';
import getimage from './getImage';
import listusers from './listUsers';
import setUserRoleOnCreate, { setUserRoleOnSignIn } from './setUserRoleOnCreate';
import populatedatabasefromsubsplash from './Scrapers/populateDatabaseFromSubsplash';
import createnewsubsplashlist from './createNewSubsplashList';
import deletesubsplashlist from './deleteSubsplashList';
import editsubsplashlist from './editSubsplashList';
import addtolist from './addToList';
import removefromlist from './removeFromList';
import uploadtosoundcloud from './uploadToSoundCloud';
import deletefromsoundcloud from './deleteFromSoundCloud';
import editSubsplashSermon from './editSubsplashSermon';
import editSoundCloudSermon from './editSoundCloudSermon';
import exchangeSoundCloudAuthCode from './exchangeSoundCloudAuthCode';
import getSoundCloudAuthStatus from './getSoundCloudAuthStatus';
import listItemOnDelete from './DocumentListeners/Lists/listItemOnDelete';
import listItemOnCreate from './DocumentListeners/Lists/listItemOnCreate';
import listOnDelete from './DocumentListeners/Lists/listOnDelete';
import listOnUpdate from './DocumentListeners/Lists/listOnUpdate';
import sermonListOnCreate from './DocumentListeners/SermonLists/sermonListOnCreate';
import sermonListOnDelete from './DocumentListeners/SermonLists/sermonListOnDelete';
import sermonListOnUpdate from './DocumentListeners/SermonLists/sermonListOnUpdate';
import sermonOnDelete from './DocumentListeners/Sermons/sermonOnDelete';
import sermonWriteTrigger from './DocumentListeners/Sermons/sermonWriteTrigger';
import repopulatelistfromspeakeritems from './Scrapers/repopulateListFromSpeakerItems';
import getuser from './getUser';
import getusersbyids from './getUsersByIds';
import fixsermonCounts from './fixSermonCounts';
import { createTopicBundle } from './createTopicBundle';
import topicOnWrite from './DocumentListeners/Topics/topicOnWrite';
import { createSubtitleBundle } from './createSubtitleBundle';
import subtitleListOnWrite from './DocumentListeners/Lists/subtitleListOnWrite';
import { createBibleChapterBundle } from './createBibleChapterBundle';
import { createSundayHomilyBundle } from './createSundayHomilyBundle';
import { createLatestListBundle } from './createLatestListBundle';
import { bibleChapterListOnWrite, sundayHomilyListOnWrite } from './DocumentListeners/Lists/taggedListOnWrite';
import { fixPhantomListItems } from './Scrapers/fixPhantomListItems';
import { updateSubsplashTag } from './Scrapers/updateSubsplashTag';
import { updateImageMetadata } from './helpers/updateImageMetadata';
import imageOnDelete from './DocumentListeners/Images/imageOnDelete';
import seriesItemOnWrite from './DocumentListeners/Series/seriesItemOnWrite';
import createrolerequest from './roleRequests/createRoleRequest';
import listrolerequests from './roleRequests/listRoleRequests';
import acceptrolerequest from './roleRequests/acceptRoleRequest';
import denyrolerequest from './roleRequests/denyRoleRequest';
import createinvite from './invites/createInvite';
import claiminvite from './invites/claimInvite';
import listinvites from './invites/listInvites';
import revokeinvite from './invites/revokeInvite';
import resendinvite from './invites/resendInvite';
import createspeaker from './speakers/createSpeaker';
import updatespeaker from './speakers/updateSpeaker';
import deletespeaker from './speakers/deleteSpeaker';
import getlistoverflowchain from './getListOverflowChain';

// Series functions
import createseries from './createSeries';
import deleteseries from './deleteSeries';
import addtoseries from './addToSeries';
import removefromseries from './removeFromSeries';
import reorderseriesitems from './reorderSeriesItems';
import bulkaddtoseries from './bulkAddToSeries';
import reorderlistitems from './reorderListItems';

exports.uploadToSubsplash = uploadToSubsplash;
exports.editSubsplashSermon = editSubsplashSermon;
exports.editSoundCloudSermon = editSoundCloudSermon;
exports.exchangeSoundCloudAuthCode = exchangeSoundCloudAuthCode;
exports.getSoundCloudAuthStatus = getSoundCloudAuthStatus;
exports.deletefromsubsplash = deleteFromSubsplash;
exports.setuserrole = setuserrole;
exports.addintrooutrotaskhandler = addintrooutrotaskhandler;
exports.addintrooutrotaskgenerator = addintrooutrotaskgenerator;
exports.uploadimage = uploadimage;
exports.getimage = getimage;
exports.listusers = listusers;
exports.getuser = getuser;
exports.getusersbyids = getusersbyids;
exports.setuserroleoncreate = setUserRoleOnCreate;
exports.setuserroleonsignin = setUserRoleOnSignIn;
exports.populatedatabasefromsubsplash = populatedatabasefromsubsplash;
exports.createnewsubsplashlist = createnewsubsplashlist;
exports.deletesubsplashlist = deletesubsplashlist;
exports.editsubsplashlist = editsubsplashlist;
exports.addtolist = addtolist;
exports.removefromlist = removefromlist;
exports.saveimage = saveimage;
exports.uploadtosoundcloud = uploadtosoundcloud;
exports.deletefromsoundcloud = deletefromsoundcloud;
exports.sermonwritetrigger = sermonWriteTrigger;
exports.sermonOnDelete = sermonOnDelete;
exports.listondelete = listOnDelete;
exports.listonupdate = listOnUpdate;
exports.listitemondelete = listItemOnDelete;
exports.listitemoncreate = listItemOnCreate;
exports.sermonlistoncreate = sermonListOnCreate;
exports.sermonlistondelete = sermonListOnDelete;
exports.sermonlistonupdate = sermonListOnUpdate;
exports.repopulatelistfromspeakeritems = repopulatelistfromspeakeritems;
exports.updatecreatedandeditedatmillis = updatecreatedandeditedatmillis;
exports.tagitemsinlist = tagitemsinlist;
exports.generatesecuredapikey = generatesecuredapikey;
exports.fixsermoncounts = fixsermonCounts;
exports.createtopicbundle = createTopicBundle;
exports.topiconwrite = topicOnWrite;
exports.createsubtitlebundle = createSubtitleBundle;
exports.subtitlelistonwrite = subtitleListOnWrite;
exports.createbiblechapterbundle = createBibleChapterBundle;
exports.createsundayhomilybundle = createSundayHomilyBundle;
exports.createlatestlistbundle = createLatestListBundle;
exports.biblechapterlistonwrite = bibleChapterListOnWrite;
exports.sundayhomilylistonwrite = sundayHomilyListOnWrite;
exports.fixphantomlistitems = fixPhantomListItems;
exports.updatesubsplashtag = updateSubsplashTag;
exports.updateimagemetadata = updateImageMetadata;
exports.imageondelete = imageOnDelete;
exports.seriesitemonwrite = seriesItemOnWrite;
exports.createrolerequest = createrolerequest;
exports.listrolerequests = listrolerequests;
exports.acceptrolerequest = acceptrolerequest;
exports.denyrolerequest = denyrolerequest;
exports.createinvite = createinvite;
exports.claiminvite = claiminvite;
exports.listinvites = listinvites;
exports.revokeinvite = revokeinvite;
exports.resendinvite = resendinvite;
exports.createspeaker = createspeaker;
exports.updatespeaker = updatespeaker;
exports.deletespeaker = deletespeaker;
exports.getlistoverflowchain = getlistoverflowchain;

// Series exports
exports.createseries = createseries;
exports.deleteseries = deleteseries;
exports.addtoseries = addtoseries;
exports.removefromseries = removefromseries;
exports.reorderseriesitems = reorderseriesitems;
exports.bulkaddtoseries = bulkaddtoseries;
exports.reorderlistitems = reorderlistitems;
