// To deploy functions: npm run-script deploy
// To test functions: npm run-script serve

import * as admin from 'firebase-admin';
import uploadToSubsplash from './uploadToSubsplash';
import setUserRole from './setUserRole';
import addintrooutro from './addIntroOutro';
import deleteFromSubsplash from './deleteFromSubsplash';
import uploadimage from './handleImageUpload';
import saveimage from './saveImage';
import getimage from './getImage';
import listusers from './listUsers';
import setUserRoleOnCreate from './setUserRoleOnCreate';
import populatespeakerimages from './populateSpeakerImages';
import createnewsubsplashlist from './createNewSubsplashList';
import deletesubsplashlist from './deleteSubsplashList';
import addToSeries from './addToSeries';
import uploadtosoundcloud from './uploadToSoundCloud';
import deletefromsoundcloud from './deleteFromSoundCloud';
import editSubsplashSermon from './editSubsplashSermon';
import editSoundCloudSermon from './editSoundCloudSermon';
import seriesSermonOnDelete from './DocumentListeners/Series/seriesSermonOnDelete';
import seriesSermonOnCreate from './DocumentListeners/Series/seriesSermonOnCreate';
import seriesOnDelete from './DocumentListeners/Series/seriesOnDelete';
import seriesOnUpdate from './DocumentListeners/Series/seriesOnUpdate';
import sermonWriteTrigger from './DocumentListeners/Sermons/sermonWriteTrigger';
admin.initializeApp();

exports.uploadToSubsplash = uploadToSubsplash;
exports.editSubsplashSermon = editSubsplashSermon;
exports.editSoundCloudSermon = editSoundCloudSermon;
exports.deleteFromSubsplash = deleteFromSubsplash;
exports.setUserRole = setUserRole;
exports.addintrooutro = addintrooutro;
exports.uploadimage = uploadimage;
exports.getimage = getimage;
exports.listusers = listusers;
exports.setuserroleoncreate = setUserRoleOnCreate;
exports.populatespeakerimages = populatespeakerimages;
exports.createnewsubsplashlist = createnewsubsplashlist;
exports.deletesubsplashlist = deletesubsplashlist;
exports.addtoseries = addToSeries;
exports.saveimage = saveimage;
exports.uploadtosoundcloud = uploadtosoundcloud;
exports.deletefromsoundcloud = deletefromsoundcloud;
exports.sermonWriteTrigger = sermonWriteTrigger;
exports.seriesOnDelete = seriesOnDelete;
exports.seriesOnUpdate = seriesOnUpdate;
exports.seriesSermonOnDelete = seriesSermonOnDelete;
exports.seriesSermonOnCreate = seriesSermonOnCreate;
