/**
 * Website's home page
 */
'use client';
import Typography from '@mui/material/Typography';
import Stack from '@mui/system/Stack';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useAuth } from '../auth/hooks';

// Components
// import LoginPage from './login';

const Home: NextPage = () => {
  // const { user, loading } = useAuth();
  const { tenant } = useAuth();

  console.log('HOME PAGE TENANT', { tenant });

  return (
    <>
      <Head>
        <title>Upper Room Media</title>
        <meta property="og:title" content="Upper Room Media" key="title" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Stack justifyContent="center" alignItems="center" padding={2}>
        <Typography variant="h3">Welcome {tenant?.name} to the home page</Typography>
      </Stack>
    </>
  );
};

export default Home;
