/**
 * Uploader Page
 */
import type { NextPage } from 'next';
import Head from 'next/head';

import VerifiedUserUploader from '../components/uploaderComponents/VerifiedUserUploaderComponent';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Upper Room Media</title>
        <meta property="og:title" content="Upper Room Media" key="title" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <VerifiedUserUploader />
    </>
  );
};

export default Home;
