/**
 * Uploader Page
 */
import type { NextPage } from 'next';
import Head from 'next/head';

// Auth
import useAuth from '../context/user/UserContext';

import Uploader from '../components/UploaderComponent';

const Home: NextPage = () => {
  const { user } = useAuth();
  return (
    <>
      <Head>
        <title>Upper Room Media</title>
        <meta property="og:title" content="Upper Room Media" key="title" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Uploader />
    </>
  );
};

export default Home;
