/**
 * Website's home page
 */
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

// Auth
import useAuth from '../context/user/UserContext';

// Components
import PopUp from '../components/PopUp';
import Login from '../components/Login';
import Signup from '../components/Signup';
import Button from '@mui/material/Button';

const Home: NextPage = () => {
  const { user } = useAuth();

  const [signupPopupOpen, setSignupPopupOpen] = useState<boolean>(false);

  return user ? (
    <h1>Welcome to the home page</h1>
  ) : (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-around',
        alignItems: 'center',
      }}
    >
      <Head>
        <title>Upper Room Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/upper_room_media_icon.png" />
      </Head>
      <Login />
      <Button onClick={() => setSignupPopupOpen(true)}>Sign Up</Button>
      <PopUp title="" open={signupPopupOpen} setOpen={setSignupPopupOpen}>
        <Signup />
      </PopUp>
    </div>
  );
};

export default Home;
